#!/bin/bash

echo "Running git pre-commit hook..."

echo "Building docker image..."
docker build .

echo "Building app..."
docker run --rm -v "$(pwd)":/var/app cloked-timecalculator ./gradlew bootJar

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0
