name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk21-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: gradle bootJar

